/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as scoreValutForwarderSol from "./ScoreValutForwarder.sol";
export type { scoreValutForwarderSol };
import type * as interface from "./interface";
export type { interface };
import type * as verifierSol from "./verifier.sol";
export type { verifierSol };
export type { ScoreVault } from "./ScoreVault";
